// <auto-generated />
using System;
using AccidentDetectionSysrem.modelsef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccidentDetectionSysrem.Migrations
{
    [DbContext(typeof(AccidentDetectionSystemContect))]
    [Migration("20260418104405_MakeCameraIdNullable")]
    partial class MakeCameraIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Accident", b =>
                {
                    b.Property<int>("AccidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccidentId"));

                    b.Property<DateTime>("AccidentTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccidentId");

                    b.HasIndex("CameraId");

                    b.ToTable("Accidents");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Camera", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraId"));

                    b.Property<string>("CameraName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("AccidentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrafficStatusId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("AccidentId");

                    b.HasIndex("TrafficStatusId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Trafficstatus", b =>
                {
                    b.Property<int>("TrafficStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrafficStatusId"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrafficStatusId");

                    b.HasIndex("CameraId");

                    b.ToTable("Trafficstatuses");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.VehicleDetection", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.HasIndex("CameraId");

                    b.ToTable("VehicleDetections");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.user", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AccidentDetectionSystem.efmodels.UserNotifiction", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotifictions");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Accident", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Camera", "Camera")
                        .WithMany("Accidents")
                        .HasForeignKey("CameraId");

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Notification", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Accident", "Accident")
                        .WithMany("Notification")
                        .HasForeignKey("AccidentId");

                    b.HasOne("AccidentDetectionSysrem.modelsef.Trafficstatus", "TrafficStatus")
                        .WithMany("Notifications")
                        .HasForeignKey("TrafficStatusId");

                    b.Navigation("Accident");

                    b.Navigation("TrafficStatus");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Trafficstatus", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Camera", "Cameras")
                        .WithMany("TrafficStatuses")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cameras");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.VehicleDetection", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Camera", "Camera")
                        .WithMany("VehicleDetections")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("AccidentDetectionSystem.efmodels.UserNotifiction", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Notification", "notification")
                        .WithMany("Notifictionsuser")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccidentDetectionSysrem.modelsef.user", "users")
                        .WithMany("UserNotifi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("notification");

                    b.Navigation("users");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Accident", b =>
                {
                    b.Navigation("Notification");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Camera", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("TrafficStatuses");

                    b.Navigation("VehicleDetections");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Notification", b =>
                {
                    b.Navigation("Notifictionsuser");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Trafficstatus", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.user", b =>
                {
                    b.Navigation("UserNotifi");
                });
#pragma warning restore 612, 618
        }
    }
}
