// <auto-generated />
using System;
using AccidentDetectionSysrem.modelsef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccidentDetectionSysrem.Migrations
{
    [DbContext(typeof(AccidentDetectionSystemContect))]
    [Migration("20260303110231_camra")]
    partial class camra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Accident", b =>
                {
                    b.Property<int>("AccidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccidentId"));

                    b.Property<DateTime>("AccidentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccidentId");

                    b.HasIndex("CameraId");

                    b.ToTable("Accident");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Camera", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraId"));

                    b.Property<string>("CameraName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("AccidentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrafficStatusId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("AccidentId");

                    b.HasIndex("TrafficStatusId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Trafficstatus", b =>
                {
                    b.Property<int>("TrafficStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrafficStatusId"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrafficStatusId");

                    b.HasIndex("CameraId");

                    b.ToTable("Trafficstatus");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.VehicleDetection", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.HasIndex("CameraId");

                    b.ToTable("VehicleDetection");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Accident", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Camera", "Camera")
                        .WithMany("Accidents")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Notification", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Accident", "Accident")
                        .WithMany("Notification")
                        .HasForeignKey("AccidentId");

                    b.HasOne("AccidentDetectionSysrem.modelsef.Trafficstatus", "TrafficStatus")
                        .WithMany("Notifications")
                        .HasForeignKey("TrafficStatusId");

                    b.Navigation("Accident");

                    b.Navigation("TrafficStatus");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Trafficstatus", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Camera", "Cameras")
                        .WithMany("TrafficStatuses")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cameras");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.VehicleDetection", b =>
                {
                    b.HasOne("AccidentDetectionSysrem.modelsef.Camera", "Camera")
                        .WithMany("VehicleDetections")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Accident", b =>
                {
                    b.Navigation("Notification");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Camera", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("TrafficStatuses");

                    b.Navigation("VehicleDetections");
                });

            modelBuilder.Entity("AccidentDetectionSysrem.modelsef.Trafficstatus", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
